5.2 task solution
mate-academy/jv-builder pull request #113
Opened 2020-07-31 09:54 UTC by gradiviro

2020-07-31 14:56 UTC, boroda4436 requested changes

2020-07-31 14:56 UTC, boroda4436 commented on src/main/java/core/basesyntax/Plane.java
> +
redundant empty line

2020-07-31 14:56 UTC, boroda4436 commented on src/main/java/core/basesyntax/Plane.java
> +
redundant empty line

2020-07-31 14:56 UTC, boroda4436 commented on src/main/java/core/basesyntax/Plane.java
> +
a redundant empty line. Please, check all your code

2020-07-31 14:56 UTC, boroda4436 commented on src/main/java/core/basesyntax/Plane.java
> +        private PlaneBuilder() {
please add the Main class with an example of how to use your builder

2020-07-31 15:23 UTC, boroda4436 requested changes

2020-07-31 15:23 UTC, boroda4436 commented on src/main/java/core/basesyntax/Plane.java
> +        public PlaneBuilder() {
is it required? By default, we already have a default constructor

2020-08-03 07:27 UTC, dmytro-hryhoruk commented on src/main/java/core/basesyntax/Plane.java
> +    public Plane(PlaneBuilder planeBuilder) {
https://mate-academy.github.io/jv-program-fulltime/01_core/checklist/hw_05.html
check your solution according to checklist

2020-08-03 10:07 UTC, dmytro-hryhoruk approved these changes

2020-11-12 08:51 UTC, closed without merging