Build Plane with Builder functionality
mate-academy/jv-builder pull request #137
Opened 2020-07-31 14:14 UTC by fyarkiy

2020-07-31 15:05 UTC, Sofasmile commented on src/main/java/core/basesyntax/Plane.java
> +        this.brand = planeBuilder.brand;
```suggestion
        brand = planeBuilder.brand;
```

2020-07-31 15:05 UTC, Sofasmile commented on src/main/java/core/basesyntax/Plane.java
> +    Plane(PlaneBuilder planeBuilder) {
давай додамо модифікатор доступу

2020-07-31 15:05 UTC, Sofasmile commented on src/main/java/core/basesyntax/Plane.java
> +        String brand;
модифікатори

2020-07-31 15:05 UTC, Sofasmile commented on src/main/java/core/basesyntax/Plane.java
> +        public PlaneBuilder(String brand, String model) {
для чого тут конструктор?

2020-08-03 06:57 UTC, KseniiaMakarova requested changes

2020-08-03 06:57 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/Plane.java
> +        boolean turboEngine;
add access modifiers to fields

2020-08-03 11:18 UTC, KseniiaMakarova approved these changes

2020-11-12 08:51 UTC, closed without merging