solution added
mate-academy/jv-builder pull request #139
Opened 2020-07-31 14:46 UTC by DariaPikul

2020-07-31 15:06 UTC, Sofasmile commented on src/main/java/core/basesyntax/Plane.java
> +        this.model = builder.model;
```suggestion
        model = builder.model;
```

2020-07-31 15:06 UTC, Sofasmile commented on src/main/java/core/basesyntax/Plane.java
> +        return this.model;
```suggestion
        return model;
```

2020-08-03 05:54 UTC, KseniiaMakarova requested changes

2020-08-03 05:54 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/Plane.java
> +    public Plane(PlaneBuilder builder) {
we should be able to call this constructor from inside this class only
```suggestion
   private Plane(PlaneBuilder builder) {
```

2020-08-03 05:54 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/Plane.java
> +        public String companyOwner;
don't forget about field encapsulation

2020-08-03 10:58 UTC, KseniiaMakarova approved these changes

2020-11-12 08:51 UTC, closed without merging