Added solution to HW5-2
mate-academy/jv-builder pull request #140
Opened 2020-07-31 14:59 UTC by MichaelShevchenko

2020-07-31 15:03 UTC, Sofasmile commented on src/main/java/core/basesyntax/Plane.java
> +    public static class PlaneBuilder implements Builder {
чому вирішив реалізовувати через інетрфейс?

2020-07-31 15:52 UTC, MichaelShevchenko commented on src/main/java/core/basesyntax/Plane.java
> +    public static class PlaneBuilder implements Builder {
Потому что сначала реализовывал Builder отдельным классом))

2020-07-31 15:53 UTC, MichaelShevchenko commented on src/main/java/core/basesyntax/Plane.java
> +    public static class PlaneBuilder implements Builder {
done

2020-08-03 06:52 UTC, KseniiaMakarova requested changes

2020-08-03 06:52 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/MainApp.java
> +        Plane.PlaneBuilder plane2 = new Plane.PlaneBuilder();
this is not a plane
```suggestion
        Plane.PlaneBuilder planeBuilder = new Plane.PlaneBuilder();
```

2020-08-03 07:09 UTC, MichaelShevchenko commented on src/main/java/core/basesyntax/MainApp.java
> +        Plane.PlaneBuilder plane2 = new Plane.PlaneBuilder();
done

2020-08-03 11:17 UTC, KseniiaMakarova approved these changes

2020-11-12 08:51 UTC, closed without merging